org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# The Minecraft version must agree with the Neo version to get a valid artifact.
# See https://projects.neoforged.net/neoforged/neoforge for the latest versions.
minecraft_version=1.21.11
neo_version=21.11.45

group_id=sheepfromheaven.screenspec
artifact_id=screenspec-neoforge
mod_version=0.1.0

modrinth_project_id=Q9he24US
