org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# The Minecraft version must agree with the Neo version to get a valid artifact.
# See https://projects.neoforged.net/neoforged/neoforge for the latest versions.
minecraft_version=26.1.2
neo_version=26.1.2.92
userdev_version=7.1.38

group_id=dev.screenspec
artifact_id=screenspec-neoforge
mod_version=1.0.0
