org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true

# The Minecraft version must agree with the Neo version to get a valid artifact.
# See https://projects.neoforged.net/neoforged/neoforge for the latest versions.
minecraft_version=1.21.1
neo_version=21.1.176
userdev_version=7.0.170

group_id=dev.screenspec
artifact_id=screenspec-neoforge
mod_version=1.0.0
