import fs from "node:fs";
import path from "node:path";
import type { Page } from "@playwright/test";
import type { ScreenSpec, WidgetSpec } from "../../lib/types";

const SYNTHETIC_TEXTURE_DIR = path.join(__dirname, "../fixtures/textures");
const REAL_TEXTURE_DIR = path.join(__dirname, "../fixtures/real-textures");

/**
 * Every PNG in tests/fixtures/real-textures (if present and non-empty —
 * produced locally by tests/scripts/extract-real-textures.mjs from a real
 * pack, see .env), else tests/fixtures/textures (synthetic, committed,
 * generated by tests/fixtures/generate-textures.mjs). Base64-encoded, keyed
 * by filename.
 */
function loadFixtureTextures(): Record<string, string> {
  const hasReal = fs.existsSync(REAL_TEXTURE_DIR) && fs.readdirSync(REAL_TEXTURE_DIR).some((f) => f.endsWith(".png"));
  const dir = hasReal ? REAL_TEXTURE_DIR : SYNTHETIC_TEXTURE_DIR;
  const out: Record<string, string> = {};
  for (const name of fs.readdirSync(dir)) {
    if (!name.endsWith(".png")) continue;
    out[name] = fs.readFileSync(path.join(dir, name)).toString("base64");
  }
  return out;
}

const FIXTURE_TEXTURES = loadFixtureTextures();

/**
 * Seeds IndexedDB with the synthetic fixture textures (same store/schema as
 * lib/textureStore.ts) so the app skips the "load a JAR" setup screen.
 * Call before navigating to /editor/<key>.
 */
export async function seedTextures(page: Page): Promise<void> {
  await page.addInitScript((texData) => {
    (window as unknown as { __seedTexturesPromise: Promise<void> }).__seedTexturesPromise = (async () => {
      const db = await new Promise<IDBDatabase>((resolve, reject) => {
        const req = indexedDB.open("mc-ui-builder", 1);
        req.onupgradeneeded = () => req.result.createObjectStore("textures");
        req.onsuccess = () => resolve(req.result);
        req.onerror = () => reject(req.error);
      });
      for (const [name, b64] of Object.entries(texData)) {
        const bytes = Uint8Array.from(atob(b64), (c) => c.charCodeAt(0));
        const blob = new Blob([bytes], { type: "image/png" });
        await new Promise<void>((resolve, reject) => {
          const tx = db.transaction("textures", "readwrite");
          tx.objectStore("textures").put(blob, name);
          tx.oncomplete = () => resolve();
          tx.onerror = () => reject(tx.error);
        });
      }
    })();
  }, FIXTURE_TEXTURES);
}

/**
 * Seeds localStorage with a single project ("e2e") containing the given
 * screen, so /editor/e2e loads directly into it. Call before navigating.
 */
export async function seedProject(page: Page, screen: ScreenSpec, projectKey = "e2e"): Promise<void> {
  await page.addInitScript(
    ({ screen, projectKey }) => {
      const session = {
        history: [{ screens: [screen], activeIdx: 0 }],
        cursor: 0,
        gridSize: 4,
        showGrid: false,
        scale: 3,
      };
      localStorage.setItem(
        "mc-ui-builder-projects",
        JSON.stringify([{ key: projectKey, session, updatedAt: 1 }])
      );
    },
    { screen, projectKey }
  );
}

/**
 * Loads the editor for `projectKey` and waits for the seeded textures to
 * land in IndexedDB.
 *
 * Also drives the zoom level down to 1 via repeated clicks on the toolbar's
 * zoom-out button. The editor's own zoom-to-fit effect (page.tsx's
 * `computeFit`) derives scale from live layout measurements on a post-mount
 * rAF, and those measurements vary slightly between loads (font metrics,
 * sidebar paint timing) — enough to occasionally flip which integer scale
 * `Math.floor(...)` lands on. `zoomOut` is a plain `s => max(s-1, 1))`
 * reducer, so clicking it enough times always converges on exactly 1
 * regardless of whatever computeFit happened to pick, making widget
 * geometry deterministic for screenshots.
 */
export async function openEditor(page: Page, projectKey = "e2e"): Promise<void> {
  await page.goto(`/editor/${projectKey}`);
  await page.evaluate(() => (window as unknown as { __seedTexturesPromise: Promise<void> }).__seedTexturesPromise);
  await page.reload();
  const zoomOut = page.getByTitle("Zoom out (⌘-)");
  await zoomOut.waitFor({ state: "visible" });
  for (let i = 0; i < 8; i++) {
    if (await zoomOut.isDisabled()) break;
    await zoomOut.click();
  }
}

let widgetIdCounter = 9000;
/** Builds a minimal ScreenSpec containing exactly one widget, for isolated widget snapshots. */
export function screenWithWidget(widget: Omit<WidgetSpec, "id"> & { id?: string }): ScreenSpec {
  const id = widget.id ?? `${widget.type}_${++widgetIdCounter}`;
  return {
    id: "main",
    width: 320,
    height: 180,
    widgets: [{ ...widget, id }],
  };
}

interface HarnessOptions {
  widget: Omit<WidgetSpec, "id"> & { id?: string };
  scale?: number;
  interactState?: "idle" | "hovered" | "pressed";
  toggled?: boolean;
  /** Scrollbar-only: knob position 0-1 (see app/widget-test-harness/page.tsx). */
  scrollPct?: number;
}

/**
 * Loads /widget-test-harness with a single widget rendered on a solid pink
 * background — no editor chrome, no selection outline. Use for per-widget
 * visual regression snapshots (see tests/visual/*.spec.ts).
 */
export async function openWidgetHarness(page: Page, opts: HarnessOptions): Promise<void> {
  const id = opts.widget.id ?? `${opts.widget.type}_${++widgetIdCounter}`;
  await seedTextures(page);
  await page.addInitScript((config) => {
    (window as unknown as { __HARNESS_WIDGET__: unknown }).__HARNESS_WIDGET__ = config;
  }, { ...opts, widget: { ...opts.widget, id } });
  await page.goto("/widget-test-harness");
  await page.evaluate(() => (window as unknown as { __seedTexturesPromise: Promise<void> }).__seedTexturesPromise);
  await page.reload();
  await page.waitForSelector('[data-harness-state="ready"]');
}
